### ISSUE TITLE
Asking for a friendly advice

### ISSUE THREAD

**Issue by janez33** [borntofrappe/Practice-Front-End-Web-Development#107]
Hello man :) Sorry for bothering you but I didn't know how to contact you. I saw your amazing Elegant Blog posted on Facebook by CodePenChallenge (https://codepen.io/borntofrappe/full/oyeQYr/). I think your work is amazing and your knowledge of CSS and HTML. I'm wondering how did you learned all this and how do you know where certain things needs to be so you get the final result. I hope if you can tell me what steps do I need to take or where can I learn all this. I'm currently learning through Udacity Front-End Developer Course and freecodecamp.org. They say if you want to learn web development that you need to start to actually build something but I really don't know what do I want to build if I don't visualize amazing things I can build out of my knowledge. Hope you can answer me.

Regards,

Janez

**Comment by borntofrappe** [comment]
Forgot to close the issue when I answered you back on twitter. Sorry if this causes you an extra notification.
